export const REQUEST_GET_USERS = "REQUEST_GET_USERS";
export const SUCCESS_GET_USERS = "SUCCESS_GET_USERS";
export const FAIL_GET_USERS = "FAIL_GET_USERS";
export const REQUEST_GET_SUSER = "REQUEST_GET_SUSER";
export const SUCCESS_GET_SUSER = "SUCCESS_GET_SUSER";
export const FAIL_GET_SUSER = "FAIL_GET_SUSER";
export const SELECTPAGE = "SELECTPAGE";

